### ISSUE TITLE
建议:基岩版增加x64版本

### ISSUE THREAD

**Issue by lava114514** [Spectrollay/minecraft_repository#1]

**Comment by Spectrollay** [comment]
现在有几个问题
一是获得x86和x64的安装包在目前还比较麻烦
二是x64需求量太小,但安装包又很大
因此暂时没有上传这个版本的打算
方便问一下你需要这个版本的原因是什么吗

**Comment by lava114514** [comment]
主要是在Linux x64 设备上使用🫠

**Comment by Spectrollay** [comment]
改天会专门开一个帖子征求一下大家的需求,会考虑新增这两个版本
但是由于存储限制大概率也只能上传正式版

**Comment by lava114514** [comment]
正式版也够用了^⁠_⁠^

**Comment by Spectrollay** [comment]
相关特性已于#2024020203起陆续进版,请及时留意版本更新

**Comment by Spectrollay** [comment]
相关特性已全部更新至版本库
